# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pooley
tagline:          The Jekyll Butler
url:              http://roachhd.github.io/poole/
paginate:         1
baseurl:          http://roachhd.github.io/poole/
author:
  name:           Katie Ball
  url:            https://twitter.com/mektball
  email:          katie@roachhd.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
